### ISSUE TITLE
Dashes in dataset names

### ISSUE THREAD

**Issue by apetresc** [radek-sprta/ansible-role-sanoid#1]
If I'm interpreting things correctly, the top-level keys of `vars` are the dataset names you're configuring policies for. However, Ansible variable names cannot have `-` characters in them, while ZFS datasets often do. Is there any way around this?

In this particular case, the dataset I'm trying to configure a policy for is called `tank2/docker-volumes`, but

```yaml
vars:
  tank2/docker-volumes:
    recursive: "yes"
```

fails with

```
ERROR! Invalid variable name in vars specified for Play: 'tank2/docker-volumes' is not a valid variable name
```

**Comment by radek-sprta** [comment]
Looks like a design decision on my part (I avoid using dashes). I think I'll just need to change the variable to accept a list of mappings.

```yaml
sanoid_datasets:
  - name: "tank2/docker-volumes"
    recursive: "yes"
```
